### ISSUE TITLE
Hide "General" category in Settings tool if empty

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers-common-plugins#2]
The `General` category should not appear if there is nothing in it. For instance, in Superpowers Web, the Settings tool displays this:

![image](https://cloud.githubusercontent.com/assets/446986/12201883/ebaa8e94-b626-11e5-9613-9b16db08da6d.png)

This could be fixed by keeping a reference to the general section root element [when it is created](https://github.com/superpowers/superpowers-common-plugins/blob/master/settings/editors/settings/index.ts#L67) and if it is empty after all plugins have loaded their setting editors, one could set `.previousElementSibling.hidden` property to `true` at the end to hide the section header.

**Comment by bilou84** [comment]
Done here https://github.com/superpowers/superpowers-common-plugins/commit/16ca41f78e4b233bae5ee499b1ba592311d17c86
