### ISSUE TITLE
textEditorWidget: Fix cut/copy/paste shortcuts (Cmd+X/C/V) on OS X

### ISSUE THREAD

**Issue by elisee** [superpowers/superpowers-common-plugins#3]
So this is something we've fixed and broken several times. Currently, we have reports of the `Cmd+X/C/V` shortcuts not working when running in the app. When fixing them, it's important to test in both Chrome and Safari too, to ensure that the fix doesn't break them there. Also, the solution is **not** to add `keydown` or `keypress` event handlers, we need to use OS X's native "accelerator" (keyboard shortcut) support.

Theoretically, we thought [`setupElectronMenu()`](https://github.com/superpowers/superpowers-common-plugins/blob/157eb2da5e40ff0d52b7d363b9973b509efb38f1/textEditorWidget/widget/widget.ts#L87) took care of it (and I was pretty sure I tested it... ?), but maybe the accelerators don't work when it's a context menu like that on OS X and we need to add them to the Application Menu? https://github.com/atom/electron/blob/master/docs/api/menu.md#notes-on-os-x-application-menu

If that is the case, then the change will probably have to be made in http://github.com/superpowers/superpowers rather than this repository.

**Workaround:** Use Superpowers from Chrome or Safari until the app is fixed.

**Comment by bunnyhero** [comment]
I was one of the ones who reported it in the app. I tested it in safari and it works in the browser for me. You are probably correct that it has to do with the shortcuts being in the context menu but not in the application menu.

**Comment by elisee** [comment]
Fixed a few days ago by https://github.com/superpowers/superpowers/commit/1f128c3ca452bd6e3c71a7b6be8864a6c2a14549
