### ISSUE TITLE
Autocompletion widget width

### ISSUE THREAD

**Issue by John0x** [superpowers/superpowers-common-plugins#9]
Hey, the autocompletion popup (which you get by hitting ctrl + space) doesn't scale with it's content. The text within the widget clips itself.

**Comment by elisee** [comment]
Hi! Thanks for the bug report.

Can you share a screenshot of the problem?

**Comment by bilou84** [comment]
I didnt't see the issue. It's possible I already fixed that in this commit.
https://github.com/superpowers/superpowers-common-plugins/commit/26ae8a225d3207f7e4e2aee6880417fc563705ba

**Comment by elisee** [comment]
Closing for now, feel free to reopen if not fixed.
